### PR TITLE
Issue/82 illegal exception in decide

### LINKED ISSUE #82: Add IllegalArgumentException and tests for functions in Decide.java
Add IllegalArgumentException() in Decide.java functions and assertThrows() test cases.

### PR DESCRIPTION
**Pull request by Zbj0116**
Added IllegalArgumentException() in Decide.java functions and more assertThrows() test cases in DecideTest.java

### CODE REVIEW

File: src/main/java/decideProgram/Decide.java [hunk 1]
```diff
@@ -15,6 +17,15 @@ public class Decide {
     public static boolean[] computeCMV(double[] x, double[] y, Parameters params, int numPoints) {
         LIC lic = new LIC();
         boolean[] cmv = new boolean[15];
+        if (x == null || y == null || params == null) {
+            throw new IllegalArgumentException("Input arrays and parameters cannot be null");
+        }
+        if (x.length != y.length) {
```
Comment (FMurkz) [inline src/main/java/decideProgram/Decide.java:23]: This is not needed, it exists in decide()
